language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_dacfc0476f3d_key -iv $encrypted_dacfc0476f3d_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- echo -e "Host 198e3e504d5ee164.natapp.ccntStrictHostKeyChecking nontIdentityFile
  ~/.ssh/id_rsa_travis" >> ~/.ssh/config
addons:
  ssh_known_hosts: 198e3e504d5ee164.natapp.cc
install: ./installViaTravis.sh
script:
  - ./buildViaTravis.sh
  - ./gradlew codeCoverageReport
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - secure: p81PYYYYhjhp1uJHOoT9EfUia8qPMphdykCxQannWMVvIFKXF5ibi/Qd52OUIYuJT9Q5MN9GhlwCtolxmCZu44YMLi99LsoITAv6n08LAFEux1oAOXmGt3ZBllvBFtlW+jlQ5lKmbuuPue3RVbTaWzL3KCCaYQ4uKW/sP31bXic=
  - secure: AYWrIC/1JqAVyLhzlDhL163LypPpq7AliDltfey9emxzS73vB5VrGTHG45Em7xdkHN0kc1vED+UFsYks7ym1olXZPsbW29R0Gfd+p1VxCE3Cbhj7x690xNC3wIlSgWGpbgiPs7vhVN80OuNgnpz9/+WRFpKAVrYrcisbvugsDqk=
  - secure: Ai75crFDh3imkmxzNQDXIwK49appZuZTrsmdZzgH1Zl/nD33RoZPWUWeeHP0yJoicNqZlU6aEXJnk8JGDWtPIT3VNO7Rsey+yrw041rHNV6bFGpwGdQgKv5CUhRHK+gShgFgnME5THCPKvK51+li1feIoByoYVmEn0gmvcxL0yM=
  - secure: ZqBsyaFMBz3cqM7UHq0IRotTPaoBNUHrC7buiAqqhZ5JNM48a2m7ORuu/SENPFfr6xOT5KylCrvT6eD1bkQi5S2jT9Qyoju/9H/hXaAUG89dhwKOxqEE11ZGKF8DlNO/jcmchVnIkgWfEjVKc7vCAww1Y8lgxhyj4gRtnln+F+o=
